package com.ebook.test;

import cn.hutool.json.JSONUtil;

import java.util.Map;

/**
 * @BelongsProject: ebook
 * @BelongsPackage: com.ebook.test
 * @Author: LuQing
 * @CreateTime: 2024-03-25  15:28
 * @Description: 描述信息
 * @Version: 1.0
 */
public class JSONStrTest {
    public static void main(String[] args) {
        String line = "{\"titleproper\":\"紧小波框架\",\"sourceno\":\"be05c6ddc5e441b69e15876078e36f36\",\"transtitle\":\"Tight Wavelet Frame\",\"author\":[\"鲁大勇\"],\"freeterm\":[\"紧小波框架\",\"延拓原理\",\"框架提升\",\"正则性条件\",\"函数周期化\",\"函数空间刻画\"],\"abstract\":\"本学位论文主要研究了五个方面的问题:框架小波的提升;紧框架小波包的构造;依照来自延拓原理的紧小波框架展开式的依范数收敛性和点点收敛性;周期紧小波框架的构造;一些函数空间的紧小波框架系数刻画.<p><p><p><p>\\t在第二章,回顾了框架的一些基本知识,简单介绍了小波框架和Gabor框架,并给出了二者的提升方案.<p><p><p><p>\\t在第三章,我们用不同于Ron和Shen的证明方法证明了高维空间上的延拓原理(酉延拓原理和斜延拓原理),给出了来自延拓原理的紧小波框架的多尺度结构和快速算法,并给出了此类紧小波框架的提升方案.<p><p><p><p>\\t在第四章,我们证明了如果来自延拓原理的母框架小波属于L1(Rd)且具有一定的衰减性,那么它们周期化后的函数能生成L2([0,1]d)上的紧小波框架.<p><p><p><p>\\t在第五章,通过引入紧小波框架的空间结构和正则性条件,我们证明了依照来自延拓原理的紧小波框架展开式不但是依Lp-范数:1<p<∞,收敛于f,而且还是点点收敛于f.<p><p><p><p>\\t在第六章,我们依次给出了空间Lp(R),1<p<∞,Hard空间H1(R), Sobolev空间,Lipschitz空间∧σ,0<α<1,和Zygmund类∧*的紧小波框架刻画.\",\"transabstract\":\"In this dissertation, we consider the following five problems:Framelet lift-ing:Construction of tight framelet packets; Norm and pointwise convergence of tight wavelet frame expansions:Construction of periodic tight wavelet frames; Characterizations of function spaces using tight wavelet frames.<p><p><p><p>\\tIn Chapter two, we give some fundamental knowledge of frames including wavelet frames and Gabor frames, and two general lifting schemes of them.<p><p><p><p>\\tIn Chapter three, we first prove the high-dimension case of the Extension Principles (Unitary Extension Principle and Oblique Extension Principle) by dif-ferent method from that given by Ron and Shen. And then give the multireso-lution structure and the fast algorithm of tight wavelet frames generated by the Extension Principles. At last, tight wavelet frame packages and lifting schemes of such the tight wavelet frame are also given.<p><p><p><p>\\tIn Chapter four, we prove that if the mother framelets belong to L1(Rd), then the periodization of those framelets may generate a tight wavelet frame for L2([0,1]d).<p><p><p><p>\\tIn Chapter five, we prove that the tight wavelet frame expansion not only converges to f in terms of Lp-norm,1< p<∞, but also converges pointwisely to f.<p><p><p><p>\\tIn Chapter six, we give characterizations of function spaces using tight wavelet frames, such as LP(R).1< p<∞, Hard space H1(R), Sobolev spaces, Lipschitz space∧a,0< a< 1, and Zygmund class∧*.\",\"supervisor\":\"樊启斌\",\"degreelevel\":\"博士\",\"discipline\":\"应用数学\",\"graninstitution\":\"武汉大学\",\"grantedyear\":\"2011\",\"classificcode\":[\"st020\"],\"classificname\":[\"数学\"],\"uri\":[\"http://cnki.cgl.org.cn/cdmdfile/a/da201207/1011404364.nh\"] } ";
        Map map = null;
        try {
            map = JSONUtil.toBean(line, Map.class);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
        System.out.println(map);
    }
}
